### PR TITLE
Dean cleanup, fixes, freeze feature

### PR DESCRIPTION
**Pull request by daattali**
I used @jpspeng 's PR #64 as the base of my branch.

I first went through the UI to understand what exactly is in the app, and made a bunch of fixes as I went through it. Then I did a quick scan of the server code and did a few low hanging fruit fixes in the server as well, some where because of actual bugs I noticed and some were to make the code cleaner and easier to work with. Each commit message has a summary of what I did.  I also implemented the freeze feature, I hope it's what you expected!

A few small comments of patterns I saw often:
- Don't use `ifelse` on single values, it's only meant to be used on vectors. When used on atomic values, it can potentially lead to very difficult-to-find bugs. For example. `ifelse(TRUE, 1:2, 3:4` returns `1` rather than what you'd generally expect.
- Try to do as much as possible from the UI and limit how much dyamic UI you have, becuase dynamic UI is much more difficult to reason about and causes more issues like checking for non existent values and for bookmarking. For some concrete examples of what I mean by that, see https://github.com/lemdt/CovidShinyModel/commit/443d6130085d3a17045946aa8b4085bc348e01a8 or https://github.com/lemdt/CovidShinyModel/commit/f4e6c29b9b2d23b51eb9f30b11161265630d43a5 or https://github.com/lemdt/CovidShinyModel/commit/25bffb8faf5eb9f98590dcfac76cd64b27f461af . Notice that `conditionalPanel()` can come in very handy. I simplified this code in a few cases, but there are some more places where this can be done that I didn't do it.
- `fluidPage` should only be called once in the entire app. It's essentially just a div but it also brings in many css, javascripts, and does some other side effects. There are many places in the codebase that define a `fluidPage` in a small section, it's sort of like defining multiple `<body>` tags in an html page - it's invalid, but if usually works, although it could sometimes lead to weird issues.

I can easily spend another day or two, there's lots more that I can do, but I've already spent 10 hours on this so I'll stop now :)

### CODE REVIEW

**Comment by jpspeng** [comment]
@daattali thank you so much, this is great. I will review today.

**Comment by jpspeng** [comment]
Freeze feature looks great! 

I removed `data.table::melt` and replace it with `tidyr::pivot_longer` to address the deprecation issue. (And now tests are passing.) 

Otherwise looks good, no regressions seen.

**Comment by daattali** [comment]
@jpspeng let me know if you have any questions about any of my code

**Comment by jpspeng** [comment]
@daattali all good so far, it was easy to read and I did a bit of cleanup on my own code based on your suggestions. thanks so much again

**Pull request merged**
