### PR TITLE
Add tests for getBetaFromDoubling()

### LINKED ISSUE #66: Test for getBetaFromDoubling function
Write automatic tests to protect from bugs. 

https://github.com/lemdt/CovidShinyModel/blob/9dcd1c027a499d6e5cbfdf826dc2eb56bfa6e91d/R/helper.R#L7-L20

### PR DESCRIPTION
**Pull request by karawoo**
Closes #66. I've added several tests for the `getBetaFromDoubling()` function. They are all written to test the behavior of the function as it's currently written. @jpspeng, could you verify that these different cases are behaving as intended, especially that the function can accept negative doubling times?

### CODE REVIEW

**Comment by jpspeng** [comment]
This looks great, thank you so much @karawoo. The structure is clear and I can replicate it for future tests. I don't think we should have negative doubling times - maybe we can validate that it's not and set an error message if it's negative. 

Also, how do these tests work? Are they automatically run every time a new code change is made on github or do they have to be manually run? 

Thanks so much again for your help.

**Comment by karawoo** [comment]
> I don't think we should have negative doubling times - maybe we can validate that it's not and set an error message if it's negative.

Yeah that makes sense to me. I can go ahead and make that change if you want.

The tests are run automatically, and if you dig in to the results of the checks on this PR you can see that they run and pass:
Screen Shot 2020-04-06 at 5 21 39 PM

You can also run them locally by running `devtools::test()`

**Comment by podTockom** [comment]
Kind of tagging on this thread - but might be good to add Travis or AppVeyor when the package is in the final stages. Then the tests will be run automatically, along with lots of different custom checks. Like this, each user would have to manually run devtools::test() to check if tests pass

**Comment by karawoo** [comment]
@podTockom that's actually already set up (using GitHub Actions)! You should see the results of the checks at the bottom of this PR:

**Comment by karawoo** [comment]
@jpspeng do you want to preserve the other behaviors that I added tests for as well? Should this function continue to accept multiple values for either argument, and should it allow NAs? I ask because this also affects how we change it to prevent doubling times <= 0.

**Comment by jpspeng** [comment]
@podTockom thanks for the suggestions! of course feel free to post on any issue if you have any more comments/feedback. 

@karawoo - sounds good. could you make the change to exclude negative doubling times? I think other behaviors (multiple values, NAs) are good. thank you!!

**Comment by karawoo** [comment]
@jpspeng I just pushed an update, let me know how this looks to you. I also added error handling for the case when non-numeric doubling times are provided, otherwise the error messages are a little cryptic.

**Pull request merged**
